version: '3.8'

services:
    database:
      image: postgres:latest
      container_name: ${PROJECT_NAME}_POSTGRES
      restart: unless-stopped
      volumes: 
        - db:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      env_file:
        - .env

    phppgadmin:
      image: docker.io/bitnami/phppgadmin:7
      container_name: ${PROJECT_NAME}_PHPPGADMIN
      environment:
        - DATABASE_HOST=database
      ports:
        - '8080:8080'
        - '443:8443'
      depends_on:
        - database

    nestjs:
      container_name: ${PROJECT_NAME}_NESTJS
      restart: unless-stopped
      build:
        context: ./
        dockerfile: Dockerfile-back
      working_dir: /backend
      ports:
        - 8000:8000
      env_file:
            - .env
      volumes:
          - node_modules_nestjs:/backend/node_modules
          - ./animal-shelter-back/animal-shelter:/backend
      depends_on:
        - database
      links:
        - database

    address-microservice:
      container_name: ${PROJECT_NAME}_NESTJS_ADDRESS
      restart: unless-stopped
      build:
        context: ./
        dockerfile: Dockerfile-address
      working_dir: /backend
      ports:
        - 8888:8888
      env_file:
            - .env
      volumes:
          - node_modules_nestjs:/backend/node_modules
          - ./animal-shelter-back/address:/backend
      depends_on:
        - database
      links:
        - database

    angular:
      container_name: ${PROJECT_NAME}_ANGULAR
      restart: unless-stopped
      build:
        context: ./
        dockerfile: Dockerfile-front
      working_dir: /frontend
      ports:
        - ${ANGULAR_PORT}:4200
      env_file:
            - .env
      volumes:
          - node_modules_angular:/frontend/node_modules
          - ./animal-shelter-front:/frontend


volumes:
  node_modules_nestjs:
  node_modules_angular:
  db:
